# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2f75c7c6d3f46e2f60a0744e45d282d810713ce5b773abb56d0dffbf8e1c917bba81b79942c8a235e0ffbb25c8190d188d687e272a1f51a89e54f9a50d706bb

test:
  secret_key_base: 5b1bde7a46d8cc6dd035910dbd99ac22a14d0c3ca4d9d3e8fea70ee9c265199b40d5aa331ccba0c1abab572451fe7a09b35fd90ad27faf13955045702daeb2a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
